SA-40: Create CI config file
SprainedAnkleApp/frontend pull request #11
Opened 2021-04-11 13:29 UTC by kdebiec

2021-04-11 14:10 UTC, kaszubab approved these changes

2021-04-11 17:59 UTC, kaszubab requested changes

2021-04-11 17:59 UTC, kaszubab commented on .github/workflows/react-build-test.yml
>          run: npm build
Wydaje mi się że tu musi być
`npm run build`

2021-04-12 12:34 UTC, AlexMaz99 approved these changes

2021-04-12 12:41 UTC, kaszubab approved these changes

2021-04-12 12:49 UTC, merged