Form fields
SprainedAnkleApp/frontend pull request #30
Opened 2021-05-15 14:20 UTC by andpodob

dodałem pola do formularza oraz walidację ich

2021-05-16 15:06 UTC, AlexMaz99 approved these changes

2021-05-16 16:08 UTC, kaszubab requested changes

2021-05-16 16:08 UTC, kaszubab commented on src/js/components/SignUp/SignUpForm.tsx
> +    console.log(data);
console.log

2021-05-16 16:08 UTC, kaszubab commented on src/js/components/common/SelectWithLabel.tsx
> +  selectProps: SelectOptions;
zamiast selectProps, rozpisałbym je tutaj, ewentualnie 
```suggestion
  export type SelectWithLabelProps = InputHTMLAttributes<HTMLSelectElement> & {
  label: string;
  error?: ErrorType;
  ...SelectOptions;
```

2021-05-16 16:08 UTC, kaszubab commented on src/js/components/common/SelectWithLabel.tsx
> +            {selectProps.placeholder}
Rozpakowałbym te wartości

2021-05-16 16:08 UTC, kaszubab commented on tsconfig.json
> +    "jsx": "react-jsx"
React-jsx może spowodować wyświetlenie się błędów u niektórych członków projektu (np u mnie :cry:  ), nie pushujmy tej zmiany

2021-05-17 15:46 UTC, kaszubab approved these changes

2021-05-20 17:27 UTC, merged