Sa 160 add reactions
SprainedAnkleApp/frontend pull request #45
Opened 2021-05-31 19:58 UTC by andpodob

Dodałem możliwość dodawania i usuwania reakcji `LIKE`. Postulował bym abyśmy pozbyli się pozostałych reakcji, jako że mam niecały tydzień żeby mieć coś sensownie działajacego :/

2021-05-31 20:22 UTC, kaszubab requested changes

2021-05-31 20:22 UTC, kaszubab commented on src/js/components/Peak/PeakDescription.tsx
> +                      text="Zatwierdz"
Literówka

2021-05-31 20:22 UTC, kaszubab commented on src/js/components/Peak/PeakDescription.tsx
> +      {true && (
Ogólnie to wyciągnął bym to z tego przycisku i podpiał pod przycisk zdobądź na karcie szczytu. Nie jest nam potrzebny dodatkowy przycisk

2021-05-31 20:22 UTC, kaszubab commented on src/js/components/common/Post/Posts.tsx
> +          currentUserId={currentUserId}
Nie musimy przekazywać tego przez propsy, mamy od tego context

2021-05-31 20:22 UTC, kaszubab commented on src/js/components/common/Post/Post.tsx
> +  const [reactionsCount, setReactionsCount] = useState(
Potrzebujemy oddzielnej liczby reakcji także dla watch, patrząc na mocki

2021-05-31 20:22 UTC, kaszubab commented on src/js/components/common/Post/Post.tsx
> +              if (toggle) {
Może przenieść zmianę ilości reakcji do funkcji `reactionToggle`

2021-05-31 20:22 UTC, kaszubab commented on src/js/components/common/Post/Post.tsx
> +                setReactionsCount(reactionsCount + 1);
Też popełniłem ten błąd w reactionToggle ale jeśli w chcemy użyć w useState starej wartości do ustalenia nowej wartości stanu wykorzystujemy funkcję 
```
                setReactionsCount(reactionsCount => reactionsCount + 1);
```

2021-05-31 20:22 UTC, kaszubab commented on src/js/views/Peak/PeakDetails.tsx
> +            currentUserId={currentUserId ? currentUserId : -1}
Tego nie musimy przekazywać, a swoją drogą lepiej obsługiwac nulle niż -1

2021-05-31 20:22 UTC, kaszubab commented on src/js/API/reactions/methods.ts
> +  type: string
zamiast stringa lepsze będzie ``
```
  type: 'LIKE' | 'LOVE'
```

2021-06-06 10:55 UTC, AlexMaz99 commented
Reakcje nie są już zmergowane przypadkiem?

2021-06-10 18:49 UTC, closed without merging